# fly.toml app configuration file generated for reactivties on 2023-04-29T18:15:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivties"
primary_region = "waw"

[build]
  image = "adamstaniszewski/reactivities2:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dykpyeevo"
  Cloudinary__ApiKey="661263559775224"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
